# Generated by Django 2.1.7 on 2019-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_file_file_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='delete_format_tag',
            field=models.BooleanField(default=False, verbose_name='Delete Format Tag'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.FileField(upload_to='media/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='progress',
            field=models.IntegerField(blank=True, default=0, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source_lang',
            field=models.CharField(default='', max_length=8, verbose_name='Source Language'),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='file',
            name='target_lang',
            field=models.CharField(default='', max_length=8, verbose_name='Target Language'),
        ),
    ]
