# Generated by Django 2.1.7 on 2019-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_auto_20190522_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_session_key', models.CharField(default='', max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('status', models.CharField(default='', max_length=16, verbose_name='Status')),
                ('source_lang', models.CharField(default='', max_length=8, verbose_name='Source Language')),
                ('target_lang', models.CharField(default='', max_length=8, verbose_name='Target Language')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('chara_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Character Count')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='delete_format_tag',
            field=models.BooleanField(default=False, verbose_name='Delete Format Tags'),
        ),
    ]
