# Generated by Django 2.2.2 on 2019-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0008_auto_20190530_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='delete_flag',
            field=models.BooleanField(blank=True, default=0, verbose_name='Deleted'),
        ),
    ]
