# Generated by Django 2.2.2 on 2020-06-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0010_file_change_to_jotai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name='Status')),
                ('source_lang', models.CharField(default='', max_length=8, verbose_name='Source Language')),
                ('target_lang', models.CharField(default='', max_length=8, verbose_name='Target Language')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('document', models.FileField(upload_to='media/glossary', verbose_name='File')),
            ],
        ),
    ]
