# Generated by Django 2.2.2 on 2020-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0011_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='terms',
            field=models.IntegerField(blank=True, default=0, verbose_name='Terms'),
        ),
    ]
