# Generated by Django 2.2.2 on 2020-07-01 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0015_remove_glossary_glossary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='glossary_to_use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translate.Glossary'),
        ),
    ]
