# Generated by Django 2.1.7 on 2019-03-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name='ステータス')),
                ('progress', models.IntegerField(blank=True, default=0, verbose_name='進捗')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='変更日')),
            ],
        ),
    ]
