# Generated by Django 2.1.7 on 2019-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0007_auto_20190522_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chara_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Character Count'),
        ),
        migrations.AddField(
            model_name='file',
            name='ip_address',
            field=models.GenericIPAddressField(default='', verbose_name='IP Address'),
        ),
    ]
