# Generated by Django 2.2.2 on 2020-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0009_file_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='change_to_jotai',
            field=models.BooleanField(default=False, verbose_name='Change to Jotai'),
        ),
    ]
