# Generated by Django 2.2.2 on 2020-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0013_glossary_glossary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='glossary_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Glossary ID'),
        ),
    ]
