# Generated by Django 2.2.2 on 2020-06-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0014_auto_20200619_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossary',
            name='glossary_id',
        ),
    ]
